### ISSUE TITLE
[v6] rc.1 FieldArray.remove + immutable causes "TypeError: list.splice is not a function" 

### ISSUE THREAD

**Issue by jc091** [erikras/redux-form#1269]
```
const renderBranchs = ({fields}) => {
  return (
    <section>
      <ButtonToolbar>
        <Button onClick={() => fields.push(Immutable.Map({}))}>Add Branch</Button>
      </ButtonToolbar>
      <br/>
      {
        fields.length > 0 ?
        (
          <Well>
            {fields.map((branch, index) =>
              <li key={index}>
                <Button
                  type="button"
                  title="Remove Branch"
                  onClick={() => fields.remove(index)}>
                  Remove
                </Button>
                <h4>Branch #{index + 1}</h4>
                <Field
                  controlId={`${branch.controlId}Name`}
                  name={`${branch}.name`}
                  type="text"
                  component={InputField}
                  placeholder="Name"
                  label="Name"/>
              </li>
            )}
          </Well>
        ) : null
      }
    </section>
  );
};
```

I got the  issue when I add a field, touch the field and try to remove it.

version: "v6.0.0-rc.1"

https://github.com/erikras/redux-form/blob/v6.0.0-rc.1/src/structure/immutable/index.js#L17
I was trying to debug the issue.
structure.splice functoin was called twice.
For the second structure.splice function call, the variable list was a Immutable.Map instead of a Immutable.List

**Comment by jccf091** [comment]
![img_0430](https://cloud.githubusercontent.com/assets/4727258/16545502/90c876fc-415f-11e6-925e-c289390220af.JPG)

**Comment by Pongetti** [comment]
This is clearly related to #1082 which was fixed in alpha 15 for the FieldArray.push but actually remained for FieldArray.remove

**Comment by jccf091** [comment]
I guess the issue is in the code in reducer.js
```
var doSplice = function doSplice(state, key, field, index, removeNum, value, force) {
    var existing = getIn(state, key + '.' + field);
    return existing || force ? setIn(state, key + '.' + field, splice(existing, index, removeNum, value)) : state;
  };
```
For FieldArray.push case, the var existing will be undefined.
For FieldArray.remove case, the var existing will be Map.
`var existing = getIn(state, "fields.branchs");`
```
getIn(state, "values.branchs")
List {size: 1, _origin: 0, _capacity: 1, _level: 5, _root: null…}
getIn(state, "fields.branchs")
Map {size: 1, _root: ArrayMapNode, __ownerID: undefined, __hash: undefined, __altered: false}
``` 
Is it expected?

**Comment by nktssh** [comment]
any updates on this?
Issue is still present...

**Comment by marcosideame** [comment]
@erikras, any solution ???

**Comment by oakley808** [comment]
I'm seeing this issue in the newly released v6.0.1. I agree with @Pongetti this looks like #1082

**Comment by Reanmachine** [comment]
I believe this should be fixed by my PR #1716. The problem is that when you "touch" a field in a field array immutable-js' `setIn` method initializes the state like this:

```
{
  fields: {
    collection: {
      "0": { touched: true }
    }
}
```

Instead of what it expects:
```
{
  fields: {
    collection: [
      { touched: true }
    ]
  }
}
```

Either we need to stop relying on `FieldArray` values being indexed numerically in an array-like structure or we need to implement something like my PR has, which is to ensure array paths are created ahead of time so `immutable-js` can't take liberties when it creates the deep nested structure.

**Comment by igorbarbashin** [comment]
Confirming that it's still happening in v6.0.2
I haven't tested but hoping @Reanmachine's PR will fix it!

**Comment by Frit** [comment]
so, how to solve this issue?
v6.0.2

**Comment by Reanmachine** [comment]
@Frit as a temporary solution you can probably prevent `onFocus` and `onBlur` from triggering as they're usually the culprit for initializing the field(s) in the incorrect way. Unfortunately I wasn't able to find a solid workaround without making modifications to `setIn` on the immutable structure in `redux-form`.

**Comment by Frit** [comment]
@Reanmachine, so I found your fork and replaced base redux-form, now it works, thank you =)

**Comment by Reanmachine** [comment]
@Frit I believe it was merged into the latest official build.

**Comment by Palid** [comment]
Looks like this one's fixed in the latest release.
Same problem was here: https://github.com/erikras/redux-form/issues/1082

Probably can close?
@Reanmachine, @erikras

**Comment by erikras** [comment]
Yep. Thanks @Palid.
