### ISSUE TITLE
Reducer import error

### ISSUE THREAD

**Issue by pavel06081991** [erikras/redux-form#1637]
I'm using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) which uses webpack 2. I installed redux-form(version 6.0.1) and did this:

`import { reducer as form } from 'redux-form/immutable';`

Note that I only tried to import the reducer, I did not even try to use it, just imported. And after building and running my application I get the error in browser console:
`
SubmissionError.js?3964:17Uncaught TypeError: Super expression must either be null or a function, not object`

I thought that maybe the problem is in immutable version of redux-form and tried to import the reducer of not immutable version and got the same error.

**Comment by pavel06081991** [comment]
https://github.com/mxstbr/react-boilerplate/issues/920

**Comment by pavel06081991** [comment]
https://github.com/mxstbr/react-boilerplate/issues/920

**Comment by pavel06081991** [comment]
> 
> 
>     Can we reopen this issue?
> 
> This is an issue with redux-form and what it specifies in the jsnext:main field, not an issue with react-boilerplate.
> 
> Please add an issue on the redux-form repo and tell them to properly use the jsnext:main field like all other package authors. /cc @erikras
>

**Comment by fforres** [comment]
Just bumped on the same issue, would be great to see the fix 👍

**Comment by sourcesoft** [comment]
I'm experiencing the exact same issue.

**Comment by luandro** [comment]
No ideas on how to solve this?

**Comment by sourcesoft** [comment]
@luandro It's not a fix but https://github.com/mxstbr/react-boilerplate/issues/868

**Comment by erikras** [comment]
[`v6.0.2`](https://github.com/erikras/redux-form/releases/tag/v6.0.2) should fix this issue.

**Comment by luandro** [comment]
@erikras, I just updated to `v6.0.2` but I'm still getting the same error:

`?d41d:7 Dynamic page loading failed TypeError: Super expression must either be null or a function, not object(…)`

Any thoughts? Mind re-opening this?

**Comment by sourcesoft** [comment]
@luandro after npm i --save redux-form
``
npm run build:dll
``
then npm run start again in react-boilerplate

**Comment by luandro** [comment]
Worked! Thanks @sourcesoft

**Comment by meilers** [comment]
The problem is back with 6.2 unfortunately :( @erikras

**Comment by nndung179** [comment]
this problem is backed to version 6.2 @erikras

**Comment by redism** [comment]
I'm having the same issue, and I could fix the problem after changing `package.json` file of `es6-error` package like the following.

`"jsnext:main": "./lib/index.jsnext.js",` to `"jsnext:main": "./lib/index.js",`

**Comment by zavan** [comment]
I'm also having this problem with 6.2.

The problem seems to be that ExtendableError is null or something else: https://github.com/erikras/redux-form/blob/d6bec04e5f7f9e5f263af8d393497ca6c7ebdb78/src/SubmissionError.js#L1-L3

**Comment by maticrivo** [comment]
still having issues with this on 6.2

**Comment by JustinJKlein** [comment]
Thanks a ton guys! I got my redux-form 6.2 working with react boilerplate thanks to this fix.

**Comment by jacobk** [comment]
I'm not very knowledgable on webpack but here's some speculation:

It's caused by `redux-form` specifying a `jsnext:main` property but we are importing `redux-form/immutable` _directly_, hence bypassing the specified `"jsnext:main": "./es/index.js"` (this goes on to only include files in the `/lib/*` dir). 

Exactly why this breaks I don't know but `_es6Error` gets doubly wrapped with `.default` which causes the exception since a constructor function is expected and not and object.

![image](https://cloud.githubusercontent.com/assets/497477/20466186/6f87029c-af6e-11e6-8b58-4771bef4fd6f.png)

The reason it worked in previous versions was that `es6-error": "^3.1.0`(which was used by redux-form) was built with a different `jsnext` setup (I think it was untranspiled) making me think it was two wrongs that cancelled each other.

https://github.com/rollup/rollup/issues/126 seems to suggest that it might be needed to publish two separate packages two work around this.

Regarding react-boilerplate and https://github.com/mxstbr/react-boilerplate/issues/1244 RBP is setup to always favor jsnext entires. Changing the order of `resolve.mainFields` and put `main` before `jsnext:main` in the webpack config fixes the issue to (but I don't know what else it changes)

**Comment by jacobk** [comment]
I think the cause is addressed by https://github.com/webpack/webpack/pull/3268 https://github.com/webpack/webpack/issues/3168

Basically Webpack fails to handle imports of es6 modules from es5 code which is what's happening above when the `jsnext:main` version of `es6-error` is required from inside the es5 version of redux-form.

**Comment by carlos-peru** [comment]
I run into to this regression as well in 6.2. @erikras, this is definitely a regression.

The workaround is still going to internals/webpack/webpack.base.babel.js and swap 'main' and 'jsnext:main' as below.

    mainFields: [
      'browser',
      'jsnext:main',
      'main',
    ]

to:

    mainFields: [
      'browser',
      'main',
      'jsnext:main',
    ]

**Comment by jacobk** [comment]
@carlos-peru yupp, that's what I'm doing atm, but I think that effectively disables webpack tree shaking.

**Comment by danielo515** [comment]
If the suggested change the only way to workaround this? I don't like making deep changes to template internals. Mostly because I tend to forget about them.

In any case, thanks to @jacobk and @carlos-peru for the clean explanation about what is happening and how to workaround it.

**Comment by alexidsa** [comment]
@erikras Any ideas on this issue? It's still present in 6.4.3

**Comment by gustavohenke** [comment]
PRs are welcome.

**Comment by romainquellec** [comment]
Any news on this ?

**Comment by sudheeshcm** [comment]
@erikras 

I also got this issue. 
![image](https://user-images.githubusercontent.com/13598040/29119553-39aad8cc-7d24-11e7-820f-f1f713a6672b.png)

Reached up till this issue due to the issue [initialValues not getting rendered in Field even though the store is updated with initialValues/values](https://github.com/erikras/redux-form/issues/1744).
I'm currently having this issue.

Thanks,
Sudheesh
