### ISSUE TITLE
submitSucceeded is set on redux-form/STOP_SUBMIT

### ISSUE THREAD

**Issue by theKashey** [erikras/redux-form#2260]
1. Get a form with onSubmitHandler, that will return rejected promise
2. Do remote submit.

Event flow:
> redux-form/START_SUBMIT
 submitting: true
> redux-form/STOP_SUBMIT
 submitting: undefined
 **submitSucceeded: true**
> redux-form/SET_SUBMIT_FAILED
 submitSucceeded: undefined
 submitFailed: true

**Comment by nktssh** [comment]
confirm, promise rejection is not working (

**Comment by cdaringe** [comment]
are you confident that your form looks like...

`<Form onSubmit={handleSubmit(doAsyncSubmit} />`

vs

``<Form onSubmit={doAsyncSubmit} />`?

**Comment by theKashey** [comment]
@cdaringe - no, for remote submit you have to use onSubmit prop of reduxForm.
So
reduxForm({
 onSubmit:() => Promise.reject()
}, ({handleSubmit})<form onSubmit={handleSubmit}>...</form>);

The problem is not how onSubmit work. It work fine. 
The problem occurs then you observing state (see https://github.com/erikras/redux-form/pull/2289). You will have a `moment` then your _failed_ form is _succeeded_!

**Comment by cdaringe** [comment]
ah, looks like both syntaxes are equivalent, http://redux-form.com/6.3.1/docs/api/ReduxForm.md .  anyway, bummer!

**Comment by danielrob** [comment]
@theKashey this issue is getting quite old, could you confirm that it still exists?

**Comment by theKashey** [comment]
@danielrob - according to http://redux-form.com/7.0.3/examples/remoteSubmit/ - everything is ok.
Look like issue was solved.

**Comment by pakokrew** [comment]
I confirm that even with 7.0.3 we still have this issue.
When `onSubmit` is called and return a rejected promise, the event *STOP_SUBMIT* sets `submitSucceeded` to true before that *SET_SUBMIT_FAILED* sets it to `false` and `submitFailed` to `true`

**Comment by pakokrew** [comment]
As far as I can read on :
https://github.com/erikras/redux-form/blob/171ed689cf998774c39bcd435d73dd8228cb7e02/src/createReducer.js#L391
and
https://github.com/erikras/redux-form/blob/0975a24c5ec3e82302cf2141f79ba2c46814de48/src/handleSubmit.js#L68

This happens when the rejection object is not an instance of `SubmissionError`.
I think that the submitSucceeded should not be passed to true when the Promise is rejected, even if we don't throw a `SubmissionError` instance.
(The reducer thinks it's not an error otherwise)

**Comment by stefan-dimitrov** [comment]
Seems like it's a leftover from issue #853 (pr #1428). I guess back then the `setSubmitSucceeded` action was not implemented.
So I believe now this behavior should be removed from `stopSubmit`.

**Comment by stefan-dimitrov** [comment]
I made a pull-request with a fix - #3830

**Comment by erikras** [comment]
Published fix in [`v7.3.0`](https://github.com/erikras/redux-form/releases/tag/v7.3.0).
