### ISSUE TITLE
Can't found example for react-native

### ISSUE THREAD

**Issue by steida** [erikras/redux-form#343]
How redux-form is supposed to be used in react-native?

**Comment by erikras** [comment]
[Like this](http://erikras.github.io/redux-form/#/faq/react-native).
```js
import {reduxForm} from 'redux-form/native';
```

**Comment by steida** [comment]
Hmm, process is not defined.
![screen shot 2015-11-29 at 01 47 35](https://cloud.githubusercontent.com/assets/66249/11454783/32aaf3c6-963b-11e5-8a18-c38c08e73422.png)

**Comment by erikras** [comment]
:pager: @mattiamanzati

**Comment by erikras** [comment]
Could this have been fixed by fixing #348?

**Comment by steida** [comment]
Hmm, still doesn't work, but different error message. Any idea?

![screen shot 2015-12-01 at 03 19 52](https://cloud.githubusercontent.com/assets/66249/11490604/6b8ab5be-97da-11e5-8ac2-94f649ed15f9.png)

**Comment by erikras** [comment]
Can you open those errors?

`redux-form` doesn't make any calls to `render()`. Sounds like the problem is on your end.

**Comment by steida** [comment]
So, I tracked source code in node_modules/redux-form, trying to comment out everything until i found a line making this error.

https://github.com/erikras/redux-form/blob/4f61ea9973e11bdba56a6f120241ab638d2ad344/src/propTypes.js#L1

![screen shot 2015-12-01 at 04 23 56](https://cloud.githubusercontent.com/assets/66249/11491571/5b3c4994-97e3-11e5-981b-f7492769e7e8.png)

**Comment by erikras** [comment]
Aha! Got it. Thanks.

**Comment by erikras** [comment]
Published fix under `v3.1.6`.

**Comment by steida** [comment]
Seems to be fixed somehow.

**Comment by karthickvkumar** [comment]
Hi @erikras can u suggest me some examples of using redux-form in react native

**Comment by mattiamanzati** [comment]
I used heavily redux-Form in a production react-native app, and I would say that you can follow the tutorials For the browser Environment, and just replace the import with the /native one. Just a suggestion: Instead of using react-native inputs directly wrap them in a component which rewrites onChange(event) to onChange(newValue)

**Comment by sibeliusseraphini** [comment]
@mattiamanzati do you have any code example showing the use o redux-form with react native?

**Comment by kyaroru** [comment]
Hi, i found solution here > https://github.com/erikras/redux-form/issues/1668

**Comment by esbenp** [comment]
[I made an example repository right here.](https://github.com/esbenp/react-native-redux-form-example/tree/master/src)

[I also wrote an in-depth article about the subject here](http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/)

**Comment by sbalay** [comment]
[Here's another post with some examples](https://t.co/AGysIhRS8A). Hope it helps!

**Comment by DimitriMikadze** [comment]
[another repository with redux form and react native :)](https://github.com/DimitriMikadze/firebase-react-native-redux-starter)

**Comment by starchand** [comment]
@erikras renderInput isn't working in your example. Text gets cleared as you type

**Comment by gustavohenke** [comment]
Hi @starchand. I highly recommend you to use latest Redux Form, and follow @esbenp's article and example repo.

**Comment by sethreidnz** [comment]
@esbenp I've been working on an implementation similar to yours but I wanted to use the ReactNavigation rather than flux router so I've built my own. I can get everything showing up fine and everything, but for some reason my changes don't get reflected in the input. I.E I put in a value and it gets into Redux store and everything but the input gets set back to an empty string.

Here is my repo:

[https://github.com/sethreidnz/DontFUpYourFlight](https://github.com/sethreidnz/DontFUpYourFlight)

And here is the form itself:

[https://github.com/sethreidnz/DontFUpYourFlight/blob/master/app/components/auth/SignUp.js](https://github.com/sethreidnz/DontFUpYourFlight/blob/master/app/components/auth/SignUp.js)

Would love any feedback!

**Comment by sethreidnz** [comment]
Figured it out. As mentioned in other threads I've seen around you MUST have the form reducer at the key `form` in order for this library to work property! It's a hard one to google for!

**Comment by gustavohenke** [comment]
> you MUST have the form reducer at the key `form` in order for this library to work

This is not a must, but everything gets easier if you mount the reducer at `key`.
It gets easier because it's less configuration to do (no need to [pass `getFormState` to your forms](http://redux-form.com/6.5.0/docs/api/ReduxForm.md/#-getformstate-function-optional-), for example).

**Comment by sethreidnz** [comment]
Sorry i meant its a must if you want to use it as per the examples on the [the getting started page](https://redux-form.com/6.5.0/docs/GettingStarted.md/). Admittedly it does point out 'mounted at form' but my reading of that implies that you could just mount it anywhere without further configuration. The comment sounds like its just pointing out a fact not a requirement. I know it's not saying that but its pretty easy to make that mistake. Perhaps a note on that page would go a long way?

I saw at least 3 threads with the same issue and then finally found the answer. I was not aware of `getFormState` since I didn't read the entire docs.

**Comment by arvinsim** [comment]
I followed some examples here but instead of making a custom `Button` element, I use the `Button` version from [react-native-elements](https://github.com/react-native-community/react-native-elements).

The problem that I am seeing is that I get a `please attach method to this component` message when I press on the button.
