### ISSUE TITLE
Asynchronous Blur Validation broken in 7.2

### ISSUE THREAD

**Issue by jsonxr** [erikras/redux-form#3712]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?

The following example in the documentation works when run with the dependency 7.0.4 in the linked code sandbox. https://codesandbox.io/s/nKlYo387
When you update the dependency redux-form to latest (7.2.0) the async action happens on every key stroke.

### What is the expected behavior?
Should behave as documented in the example code.

### Sandbox Link

Exact same version as the documentation but updated to react-form@7.2.0 and added a console.log so you can see it executing if you look at javascript console.
https://codesandbox.io/s/j75xx42p3y

### What's your environment?

redux-form@7.2.0

**Comment by lama-pacos** [comment]
https://github.com/erikras/redux-form/pull/3531

**Comment by gustavohenke** [comment]
This must be fixed now with v7.2.1.

**Comment by mrmedina87** [comment]
@gustavohenke @lama-pacos 

Hello guys. I can see this thread was already closed, but the bug is still happening. The validation runs on each keystroke. This time the environment in redux-form@7.2.3 (latest) 

See:

https://codesandbox.io/s/vj75k3mxx7

I updated the package to the last version in my project, hoping the bug would be fixed but it is still happening and I do not know what to do now. 

Is there a workaround to fix this while you find the actual solution?

Thanks!
