### ISSUE TITLE
Fails to compile in react 16.6.3 saying withRef is removed

### ISSUE THREAD

**Issue by Abisar** [erikras/redux-form#4286]
### What is the current behavior?
After upgrading to react 16.6.3 and react-redux 6.0.0, it fails to compile and displays:
`withRef is removed. To access the wrapped instance, use a ref on the connected component`

### Sandbox Link
https://codesandbox.io/s/l9m2pqo6l9

If it's correct, it would be nice to have a version support range in the readme.

**Comment by abdurahmanus** [comment]
The problem with react-redux v6 which uses new Context API
https://github.com/erikras/redux-form/pull/4216

**Comment by rhys-vdw** [comment]
Is this fixed yet? The issue is open but the changelog claims to have resolved it? https://github.com/erikras/redux-form/releases/tag/v8.0.0

**Comment by crocoHS** [comment]
I have same issue. How can I do to fix this issue?

**Comment by Abisar** [comment]
@crocoHS Do an update. It has been fixed with version [8.0.0](https://github.com/erikras/redux-form/releases/tag/v8.0.0).

**Comment by The-Code-Monkey** [comment]
This isn't fixed i have nothing connected and nothing in the store apart from the form reducer yet it thows `withRef is removed. To access the wrapped instance, use a ref on the connected component`

```
  "dependencies": {
    "connected-react-router": "^6.4.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.0.3",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "3.0.0",
    "redux": "^4.0.1",
    "redux-form": "^8.2.0",
    "redux-thunk": "^2.3.0",
    "sanitize.css": "^8.0.0"
  }


thats my dependencies and redux form still errors.

**Comment by iamblackornot** [comment]
have the same issue appeared after installing and using 'ra-data-rest-hapi'
