### ISSUE TITLE
event.preventDefault is not a function in onChange(event, value, previousValue, name)

### ISSUE THREAD

**Issue by tohbansoon** [erikras/redux-form#4548]
after upgrade `react-redux` to version `7.1.1` and `redux-form` to version `8.2.6`...
i found that preventDefault object is missing from the event params...

Here is my code...

```
<Field
     component={ReduxFormRadioGroup}
     formItemProps={{ className: 'operation-hours__option-container' }}
     label='Hours of Operation'
     name='operationHoursCategory'
     onChange={this.handleCategoryChange}
/>

handleDisabledDayChange = (event, value, previousValue, name) => {
        console.log(event, value, previousValue, name)
        event.preventDefault()
        ...
        .......
}
```

in `"redux-form": "^7.2.0"` and `"react-redux": "^5.0.7"`:
console.log(event) can see the `preventDefault: ƒ preventDefault()`

in `redux-form": "^8.2.6"` and `"react-redux": "^7.1.1"`:
console.log(event) do not have `preventDefault: ƒ preventDefault()`

this in result `event.preventDefault()` is not a function and break the application!

**Comment by iamandrewluca** [comment]
@tohbansoon Can you please create a https://codesandbox.io that will replicate the problem?

**Comment by mateioprea** [comment]
@iamandrewluca https://codesandbox.io/s/broken-wave-zqz0k?fontsize=14 here it is. I just got the same problem. It doesn't work with react-select

**Comment by toxsick** [comment]
Hey guys,

having the same problem. I think this behaviour was introdured here:

https://github.com/redux-form/redux-form/issues/3446

This leads to inconsistent onChange bahaviour on Fields, because I have to know if my render component supports events or not. Not sure how to handle this consistently.

**Comment by mateioprea** [comment]
@toxsick I have removed the breaking change from #3446. If you want, you can ```npm install --save https://github.com/mateioprea/redux-form``` :)

**Comment by toxsick** [comment]
@mateioprea that's a good start and I will try that later :) Thanks for that!

Would be nice to know if there is a migration path with the official release. I'm also don't understand how to stop the propagation to the store when no event is present.

**Comment by Iuriy-Budnikov** [comment]
I have the same issue

**Comment by renatoagds** [comment]
@Iuriy-Budnikov what's your version? could you confirm if `8.3.0` didn't fixed this problem? We released a fix in change: https://github.com/redux-form/redux-form/pull/4596

**Comment by Iuriy-Budnikov** [comment]
@renatoagds here an example with react select https://codesandbox.io/s/strange-glitter-j3ipz
It works with simple input

**Comment by dereksandkamp** [comment]
`8.3.0` did not fix the problem for me.

For many of my inputs, I'm calling `input.onChange(value)` with the value of the input as the argument. These are the inputs that cause the problem. When an `onChange` is passed to the `<Field />` from above these inputs, the first argument injected into the Field's onChange is the value, not the event. Then there is no way to cancel the change event.

It is possible to fix this by updating my inputs to call `input.onChange(event)` with the event instead of the value as the first argument. Then any Field.onChange handlers will receive the event. However, this isn't ideal for some inputs because the value that is attached to the change event is not always the value that I would like to propagate.

There are likely ways to work around this, but it seems like this wasn't an intended change. Or if it was, the documentation should at least make it clear that in order to receive the event in the Field.onchange handler, you need to pass an event to input.onChange from within the input.

**Comment by armin-th** [comment]
Just want to note, this is still an issue in 8.3.7

Appreciate any work being put into this :)

**Comment by mliakos-klara** [comment]
Sill an issue with `8.3.10` :)

**Comment by aayushsaini** [comment]
Using `v8.3.9` the issue exists. Guess, it went under the radar now after the release of new form-library.
Anyway unlike @dereksandkamp mentioned the fix for their specific use-case, I'm currently opting to directly add eventListener to the component (specific html element) needed and invoke e.preventDefault().
Not the ideal solution, but works in my case.

Moreover, I cannot find the official docs for v8.3.0+

PS: Any help/workaround would be duly appreciated 🥂 😃
