### ISSUE TITLE
addField with deep values

### ISSUE THREAD

**Issue by ingro** [erikras/redux-form#468]
Hello! I'm using your excellent library with a quite complex form structure, that's my fields config:
```javascript
const fields = [
    'proposals[].arrival',
    'proposals[].departure',
    'proposals[].note',
    'proposals[].rooms[]',
    'proposals[].rooms[].name',
    'proposals[].rooms[].adults',
    'proposals[].rooms[].children'
];
```

Basically a user can create many proposals and every one could have one or more rooms in it.

When a user want to add a proposal I would also populate it with an empty room to mantain the form more user friendly, so I'm trying to do this:

```javascript
        const newProposal = {
            arrival: new Date(),
            departure: new Date(),
            note: '',
            rooms: [{
                name: 'Room 1',
                adults: 2,
                children: 0
            }]
        };

        const { fields } = this.props;
        fields.proposals.addField(newProposal);
```

But I get this error:
```
Uncaught TypeError: array.map is not a function (getValues.js:31)
```

I've tried to log what's the value that throws the error and it seems that it's the `rooms` field, which is an object with two keys, `initial` and `value`.

So maybe that could be solved by checking if `array` is indeed an Array, and if not looking if it has a `value` key which is an Array?

**Comment by ataube** [comment]
+1 for this, I am having the same issues

**Comment by ingro** [comment]
@ataube could you please share an example of your workaround? Thanks!

**Comment by ataube** [comment]
Something like this, but be aware this is really a _hacky_ workaround because I simulate the internal state structure of redux-from.

```javascript
import update from 'react-addons-update'

const form = formReducer.plugin({
  MyForm : (state, action) => {
    const {type, payload} = action
    switch(type) {
      case ActionTypes.MY_CUSTOM_ACTION:
        const {proposal} = payload
        const newState = update(state, {
          proposals : {$push : [toReduxFormSchema(proposal)]}
        })
        return newState
      default:
        return state
    }
  }
})

//HACK: redux-form expects a certain structure of its state!!
function toReduxFormSchema(proposal) {
  const {arrival, rooms} = proposal
  return {
    arrival : {initial : arrival, value : arrival},
    rooms   : rooms.map(rooms=> ({initial : rooms, value : room}))
  }
}
```

**Comment by yangit** [comment]
Not only deepValues affected but also non primitive values i.e. objects.
If I have a form `usersFrom`:
````
const fields = ['users[].name','users[].gender'];
````
And I try to 
````
fields.users.addField({name:'Bob',gender:'male'});
````
Then in the reducer I will get:
````
//Actual result
{form:
   {usersForm:
      {users:[
            {value:
               {name:'Bob', gender:'male'}
            }
         ]
      }
   }
}

//Expected result
{form:
   {usersForm:
      {users:[
            {
               name: {value:'Bob'},
               gender: {value:'male'}               
            }
         ]
      }
   }
}

````

**Comment by yangit** [comment]
Below is a relatively short fix it uses React immutability helper as `update` function and `lodash` as `_` helper.
It basically fixes whatever broken state left by native 'redux-form/ADD_ARRAY_VALUE' handler and only affects newly added items at specified paths.

````
reduxForm.reducer.plugin({userForm: handleActions({
   'redux-form/ADD_ARRAY_VALUE': (state, {value,path,index}) => {
           if (path === 'users') {
             if (_.isUndefined(index)) {index = state.items.length - 1;}
             const newValues = _.mapValues(value, v => ({value: v}));
             return update(state, {users: {$splice: [[index, 1, newValues]]}});
           }
           return state;
         }
})});
````

**Comment by hartzis** [comment]
is this related to #482 and possibly solved with [v4.0.7](https://github.com/erikras/redux-form/releases/tag/v4.0.7)?

**Comment by trashgenerator** [comment]
No, it's not solved. It's opposite situation. If you set initial value for array field explicitly like
```
 fields.proposals.addField({rooms: []});
```
you will get a error 
```
Uncaught TypeError: array.forEach is not a function(anonymous function) 
@ getValues.js:24
```

**Comment by max-mykhailenko** [comment]
Also need this. I'll try to use suggestions from comments.

**Comment by max-mykhailenko** [comment]
@yangit Where you get `handleActions ` function?

**Comment by yangit** [comment]
`react-redux` npm module

**Comment by max-mykhailenko** [comment]
More simple solution for situation:
```
myField.addField({
    name: names,
    id: Date.now(),
    // components: [1], //waiting for https://github.com/erikras/redux-form/issues/468
  });
setTimeout(() => {
    fields.components[0].components.addField(1);
});
```

**Comment by erikras** [comment]
I predicted this bug to @lukekarrys here: https://github.com/erikras/redux-form/pull/425#issuecomment-164890005

It's complicated.

**Comment by erikras** [comment]
At the moment, only flat values are supported when initializing with `addField()`.

**Comment by shilpan** [comment]
I have defined my field as: `const fields = ['placeList[].location.placeId.google']`

This fails to populate the value:
`this.props.fields.placeList.addField({location: {placeId: {google: value.place_id}}}, 0);`

Would this be in a similar vein as the problem mentioned above? How would you recommend overcoming this problem?

**Comment by max-mykhailenko** [comment]
@shilpan you can look at my solution above

**Comment by shilpan** [comment]
@max-mykhailenko can you tell me how your solution would help me? I do not have another array but instead need to populate a deeply nested key

**Comment by flaub** [comment]
I have some ideas on how to fix this:

1. Add `fields` to the `ADD_ARRAY_VALUE` action and likewise extend the `addField` method to take `fields`. This way, users can specify explicitly the shape of the data.
2. Use a common prefix to determine what the shape must look like given the position in the hierarchy that `addField` is being called. For example, if a user is doing `addField` to the `proposals[]` above, we can simply chop off that prefix and use the remainder as the `fields` to be passed to `initializeState()` in the `ADD_ARRAY_VALUE` reducer.
3. Infer the shape of the data from the `value` right before calling `initializeState()`. I don't have this algorithm fully worked out (and I'm not sure if it breaks other features), but this is a snippet to give an idea:

```
...
var keys = Object.keys(value).map(function(key) {
  return value[key] instanceof Array ? key + '[]' : key;
});
const newValue = value !== null && typeof value === 'object' ?
  initializeState(value, keys) : makeFieldValue({value});
...
```

I think option 2 is probably the most solid, but I'm not sure how to obtain the original list of fields that the user specified with the `@reduxForm` decorator by the time we're in `ADD_ARRAY_VALUE`.

**Comment by flaub** [comment]
I was able to get the above use case to work with solution 1, but it doesn't feel like the best API. I can go ahead and send a PR if you're interested.

**Comment by ingro** [comment]
Thanks @flaub , that could be a start even if, as you said, that's not the cleanest API.

**Comment by carlyle** [comment]
Would it be possible to save the form's `fields` in the state so that the schema can be looked back up when `addField` is called?

**Comment by flaub** [comment]
Actually, I'm working on a better fix... going back to option 2. I do have the context required to do it, since `props.fields` contains the original fields set by the user. I'll update my PR once I've got all tests working.

**Comment by erikras** [comment]
Fix published as [`v4.1.7`](https://github.com/erikras/redux-form/releases/tag/v4.1.7). Thanks again, @flaub!

**Comment by trashgenerator** [comment]
@flaub good job!

**Comment by ingro** [comment]
Thanks @flaub and @erikras !

**Comment by tnrich** [comment]
@flaub, can you (or anyone else) provide some more documentation on how how the addField() call should be used? 

I'm trying to call addField like this:

inserts.addField({...result[0].parsedSequence, fromFileUpload: true})

And here is what it looks like in the redux devtools:
![image](https://cloud.githubusercontent.com/assets/2730609/13299824/b2df39e4-daf1-11e5-91c1-fe4f5369f44e.png)

The addField action looks good, but the reducer doesn't seem to update appropriately (the added field is the 2nd of the two inserts in there which stays as an empty object)

Thanks for the help,
Thomas

**Comment by flaub** [comment]
What does your fields specification look like? It would need to be something like:
```
[
  "inserts[].sequence",
  "inserts[].features[]",
  "inserts[].name",
  "inserts[].extraLines[]",
  "inserts[].type",
  "inserts[].size",
  "inserts[].circular",
  "inserts[].fromFileUpload"
]
```

**Comment by tnrich** [comment]
@flaub aha! Okay I didn't realize that we needed to specify subfields to make it work. Well thanks for the help, I'll let you know if it works.

**Comment by tnrich** [comment]
Hmm, so I realized there is a difference between "deep" fields, and "complex" fields. In my case, I'd like to use addField to add a complex object to the inserts[] array, but I don't actually want to add any further deep fields. Is there a way to use addField() to add complex objects to the array, (but not "deep" fields)? 

Thanks again for the help!

**Comment by mdgbayly** [comment]
@tnrich I was also trying to do something like what I think you are asking without success.
I have a field definition like:
"entries[]"
and I want the values of entries to be fields which themselves are complex objects.
I implemented a custom component to handle the complex field value and that side of it all works fine but when I try and do something like 
`entries.addField({
   mapKey: 'abc',
   mappedValue: 123
});`

The value isn't added to the state.  addField only seems to work with objects if those objects match your deep field structure.

**Comment by tnrich** [comment]
Hey @flaub and @erikras, would it be possible to add an option for adding complex objects using the addField() api, but without needing to define a field for each value in those objects. 

Is there any reason not to allow for this functionality? 

Thanks!
Thomas

**Comment by flaub** [comment]
I'm probably missing something, but how would we know what the shape of the fields should be? How would we know that there might or might not be another array deeper in the structure? Could you provide an example and how you'd like it to work?

**Comment by mdgbayly** [comment]
From my perspective, you're probably not missing something. It's probably just my lack of understanding as to how the internals of redux form work.  I arrived at this requirement because I was trying to write a normalizer that operated on an array of deep nested fields.  I found another way to implement my requirement using a reducer plugin, so switched back to using deep fields rather than complex objects.  

But my thought was that if redux form supports:

1. arrays of fields and 
2. fields which are arrays 

(as described in the Complex Values example), then maybe it also supports fields which are complex values. e.g. rather than a field just being a simple string value, it could be an object.  Just as the app is responsible for managing the array when you have a field which is an array, can't the app also be responsible for managing a field which is a complex object (which is really all an array is?)

**Comment by flaub** [comment]
Oh, now I get it, thanks! I think this is actually a new bug, I'll see if I can write a unit test to prove the failure. It might be awhile until I can get around to it though :)

**Comment by flaub** [comment]
So, I just thought of a potential workaround, but I haven't had a chance to test it. What if you used another single field beneath the array and store the complex value on it? For instance, it could be like:
```
fields = [ 'inserts[].value' ]
```

And then you'd add the field like `addField({ value: {...your_goo_here } });`

Otherwise, it doesn't seem like you don't want to use `addField`, but rather you want to add complex objects to the top-level array. Perhaps this is a whole new feature, the ability to have an array contain complex values.

The examples cover: 
* Deep fields (arrays that have deeper fields known by redux-form)
* Complex values (a single field that has an array)

**Comment by mdgbayly** [comment]
Yeah, i think you are probably right.  I had forgotten it was the addField I was having issues with when my field was a complex object, but I realize I wrote that above.  Yeah, I don't really consider this to be a bug, because as you say, the 'API' for add field is to specify the child fields in the object you pass to addField.  I wonder if using the 'inserts[].value' approach would still fail in addField though, because would redux form interpret my 'goo' as more field names rather than complex objects.  But might be worth a try.  But this isn't that important for me right now as I think my original approach wasn't great and I prefer to use deep fields rather than complex values if possible.  Loving redux forms! :thumbsup: Thanks
